---
abstract: 'Perl extension for emulating troublesome interfaces'
author:
  - chromatic
build_requires:
  Test::Exception: '0.31'
  Test::More: '0.98'
  Test::Warn: '0.23'
  base: '0'
  overload: '0'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-MockObject
requires:
  CGI: '0'
  Carp: '0'
  Devel::Peek: '0'
  Hash::Util: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
  Test::Exception: '0.31'
  Test::More: '0.98'
  Test::Warn: '0.23'
  UNIVERSAL::can: '1.20110617'
  UNIVERSAL::isa: '1.20110614'
  fields: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-MockObject
  repository: https://github.com/chromatic/Test-MockObject.git
version: '1.20140328'
