---
name: Test-MockObject
version: 1.04
author: []
abstract: Perl extension for emulating troublesome interfaces
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: ''
  Test::Simple: 0.47
  UNIVERSAL::can: 1.11
  UNIVERSAL::isa: 0.06
  perl: 5.6.0
build_requires:
  Test::Exception: ''
provides:
  Test::MockObject:
    file: lib/Test/MockObject.pm
    version: 1.04
  Test::MockObject::Extends:
    file: lib/Test/MockObject/Extends.pm
    version: 1.04
generated_by: Module::Build version 0.2709
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
